-- AETHER STUDIO — CRM PHASE 8 MIGRATION: SALES PIPELINE, DEAL VALUES & METADATA
-- Run this SQL script in your Supabase SQL Editor or PostgreSQL database console.

ALTER TABLE leads ADD COLUMN IF NOT EXISTS estimated_value INT DEFAULT 0;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS final_value INT DEFAULT 0;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS currency VARCHAR(10) DEFAULT 'INR';
ALTER TABLE leads ADD COLUMN IF NOT EXISTS won_at TIMESTAMPTZ;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS lost_at TIMESTAMPTZ;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS lost_reason VARCHAR(255);

CREATE INDEX IF NOT EXISTS idx_leads_won_at ON leads(won_at);
CREATE INDEX IF NOT EXISTS idx_leads_lost_at ON leads(lost_at);
