-- AETHER STUDIO — CRM PHASE 42 MIGRATION: ADVANCED AGENTIC AI & AUTONOMOUS BUSINESS OPERATIONS 9.0
-- Run this SQL script in your Supabase SQL Editor or PostgreSQL database console.

CREATE TABLE IF NOT EXISTS agent_logs (
  id SERIAL PRIMARY KEY,
  action_id VARCHAR(50) UNIQUE NOT NULL,
  agent_type VARCHAR(50) NOT NULL, -- 'SALES', 'RESEARCH', 'PROJECT', 'SUPPORT', 'FINANCE', 'MARKETING', 'EXECUTIVE'
  tool_name VARCHAR(100) NOT NULL,
  status VARCHAR(50) DEFAULT 'PROPOSED', -- 'PROPOSED', 'APPROVED', 'EXECUTED', 'REJECTED'
  details JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_al_agent ON agent_logs(agent_type);
